import type { InventoryItem } from '../inventory-source'

export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    niche: 'Tech',
    dr: 75,
    traffic: 50000,
    price: 500,
    region: 'USA',
    domain: 'techblog.com',
    status: 'Available',
    createdAt: '2024-01-01T00:00:00.000Z',
    spamScore: 1,
    googleNews: true,
    mozDA: 70,
    semrushAS: 72,
    referringDomains: 1200,
    completionRate: 95,
    avgLifetime: 90,
    tat: '3-5 days',
    linkType: 'Dofollow',
    language: 'English',
    contentSize: 800,
    sampleUrls: ['https://techblog.com/article1', 'https://techblog.com/article2'],
    trafficAhrefs: 45000,
    trafficSimilarweb: 50000,
    trafficSemrush: 48000,
  },
  {
    id: '2',
    niche: 'Finance',
    dr: 65,
    traffic: 30000,
    price: 400,
    region: 'UK',
    domain: 'financenews.co.uk',
    status: 'Available',
    createdAt: '2024-01-02T00:00:00.000Z',
    spamScore: 2,
    googleNews: false,
    mozDA: 60,
    semrushAS: 63,
    referringDomains: 800,
    completionRate: 88,
    avgLifetime: 85,
    tat: '5-7 days',
    linkType: 'Dofollow',
    language: 'English',
    contentSize: 1000,
    sampleUrls: ['https://financenews.co.uk/post1'],
    trafficAhrefs: 30000,
    trafficSimilarweb: 28000,
    trafficSemrush: 32000,
  },
  {
    id: '3',
    niche: 'Health',
    dr: 80,
    traffic: 100000,
    price: 800,
    region: 'USA',
    domain: 'healthtoday.com',
    status: 'Available',
    createdAt: '2024-01-03T00:00:00.000Z',
    spamScore: 0,
    googleNews: true,
    mozDA: 78,
    semrushAS: 82,
    referringDomains: 2000,
    completionRate: 98,
    avgLifetime: 95,
    tat: '2-4 days',
    linkType: 'Dofollow',
    language: 'English',
    contentSize: 1200,
    sampleUrls: ['https://healthtoday.com/wellness', 'https://healthtoday.com/nutrition'],
    trafficAhrefs: 100000,
    trafficSimilarweb: 95000,
    trafficSemrush: 98000,
  },
  {
    id: '4',
    niche: 'Marketing',
    dr: 55,
    traffic: 15000,
    price: 300,
    region: 'Canada',
    domain: 'marketingpro.ca',
    status: 'Available',
    createdAt: '2024-01-04T00:00:00.000Z',
    spamScore: 5,
    googleNews: false,
    mozDA: 52,
    semrushAS: 55,
    referringDomains: 500,
    completionRate: 80,
    avgLifetime: 75,
    tat: '7-10 days',
    linkType: 'Nofollow',
    language: 'English',
    contentSize: 600,
    sampleUrls: ['https://marketingpro.ca/seo-tips'],
    trafficAhrefs: 15000,
    trafficSimilarweb: 14000,
    trafficSemrush: 16000,
  },
  {
    id: '5',
    niche: 'Crypto',
    dr: 70,
    traffic: 60000,
    price: 600,
    region: 'Global',
    domain: 'cryptonews.io',
    status: 'Available',
    createdAt: '2024-01-05T00:00:00.000Z',
    spamScore: 3,
    googleNews: false,
    mozDA: 68,
    semrushAS: 71,
    referringDomains: 1000,
    completionRate: 92,
    avgLifetime: 88,
    tat: '4-6 days',
    linkType: 'Dofollow',
    language: 'English',
    contentSize: 900,
    sampleUrls: ['https://cryptonews.io/bitcoin', 'https://cryptonews.io/ethereum'],
    trafficAhrefs: 60000,
    trafficSimilarweb: 58000,
    trafficSemrush: 62000,
  },
  {
    id: '6',
    niche: 'Tech',
    dr: 45,
    traffic: 8000,
    price: 200,
    region: 'India',
    domain: 'techinsider.in',
    status: 'Available',
    createdAt: '2024-01-06T00:00:00.000Z',
    spamScore: 8,
    googleNews: false,
    mozDA: 42,
    semrushAS: 46,
    referringDomains: 300,
    completionRate: 75,
    avgLifetime: 70,
    tat: '10-14 days',
    linkType: 'Dofollow',
    language: 'English',
    contentSize: 500,
    sampleUrls: ['https://techinsider.in/ai-news'],
    trafficAhrefs: 8000,
    trafficSimilarweb: 7500,
    trafficSemrush: 8500,
  },
  {
    id: '7',
    niche: 'Travel',
    dr: 60,
    traffic: 25000,
    price: 350,
    region: 'USA',
    domain: 'travelguide.com.au',
    status: 'Available',
    createdAt: '2024-01-07T00:00:00.000Z',
    spamScore: 1,
    googleNews: false,
    mozDA: 58,
    semrushAS: 61,
    referringDomains: 700,
    completionRate: 90,
    avgLifetime: 85,
    tat: '5-7 days',
    linkType: 'Dofollow',
    language: 'English',
    contentSize: 700,
    sampleUrls: ['https://travelguide.com.au/destinations'],
    trafficAhrefs: 25000,
    trafficSimilarweb: 24000,
    trafficSemrush: 26000,
  },
  {
    id: '8',
    niche: 'SaaS',
    dr: 68,
    traffic: 40000,
    price: 550,
    region: 'USA',
    domain: 'saasworld.com',
    status: 'Available',
    createdAt: '2024-01-08T00:00:00.000Z',
    spamScore: 2,
    googleNews: false,
    mozDA: 65,
    semrushAS: 69,
    referringDomains: 900,
    completionRate: 94,
    avgLifetime: 92,
    tat: '3-5 days',
    linkType: 'Dofollow',
    language: 'English',
    contentSize: 850,
    sampleUrls: ['https://saasworld.com/reviews', 'https://saasworld.com/guides'],
    trafficAhrefs: 40000,
    trafficSimilarweb: 38000,
    trafficSemrush: 42000,
  },
]
